version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=mydatabase
      - SECRET_KEY=my_secret_key_just_testing
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ADMIN=admin
      - ADMIN_PASSWORD=
      
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
